"""empty message

Revision ID: 801ecfbde80c
Revises: 
Create Date: 2019-01-20 11:11:38.169265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801ecfbde80c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('stu_name', sa.String(length=32), nullable=False),
    sa.Column('stu_class', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stu_id')
    )
    op.create_table('antidrugscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biologicalscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chinesescore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('englishscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geographyscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historyscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mathscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politicalscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speakingscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('totalscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writtenscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_id', sa.String(length=20), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.stu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writtenscore')
    op.drop_table('totalscore')
    op.drop_table('speakingscore')
    op.drop_table('politicalscore')
    op.drop_table('mathscore')
    op.drop_table('historyscore')
    op.drop_table('geographyscore')
    op.drop_table('englishscore')
    op.drop_table('chinesescore')
    op.drop_table('biologicalscore')
    op.drop_table('antidrugscore')
    op.drop_table('student')
    op.drop_table('exam')
    # ### end Alembic commands ###
