"""empty message

Revision ID: d8045b5ab95f
Revises: 0b052d21083c
Create Date: 2019-01-20 00:22:38.007806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8045b5ab95f'
down_revision = '0b052d21083c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('stu_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('exam_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], [u'exam.id'], name=u'score_ibfk_1'),
    sa.ForeignKeyConstraint(['stu_id'], [u'student.stu_id'], name=u'score_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
